apiVersion: v1
data:
  azurestorageaccountkey: dnZGSVo4YVFHdktza3dSZVFIcXc1RTRJeHRpV04zRG1Ud2pHcXFRdHVMYkhIRkFScEY3a3FCNm1LdVJSR20zNzM2SnFqQ0ZjZlI4WStBU3RPcnB2ZWc9PQ==
  azurestorageaccountname: cHJvamVjdGJvc2VhenVyZWNvc3Q=
kind: Secret
metadata:
  name: blob-secret-staging
  namespace: staging
type: Opaque