apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-input-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob-input-staging
  storageClassName: azureblob-fuse-premium