# secret-sync.yaml

apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-sync 
spec:
  vault:
    name: projectbosekeyvault # 1. name of key vault
    object:
      name: dbpass # 2. name of the akv object
      type: secret # 3. akv object type
  output: 
    secret: 
      name: dbserver # 4. kubernetes secret name
      dataKey: dbpassword # 5. key to store object value in kubernetes secret store